services:
  - type: web
    name: app
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: UPLOAD_FOLDER
        value: 'uploads'
      - key: RESULT_FOLDER
        value: 'results'
      - key: SQLITE_DATABASE_URL
        value: 'My_database'
