services:
  - type: web
    name: app
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: UPLOAD_FOLDER
        value: 'uploads'
      - key: RESULT_FOLDER
        value: 'results'
      - key: POSTGRESQL_DATABASE_URL
        fromDatabase:
          name: app-db
          property: connectionString

databases:
  - name: app-db
    plan: starter
    region: oregon
    envVars:
      - key: POSTGRES_USER
        generateValue: true
      - key: POSTGRES_PASSWORD
        generateValue: true
